# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Ranger Report
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_custom.tasks.io import (
    download_event_attachments as download_event_attachments,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import (
    load_local_spatial_file as load_local_spatial_file,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)
from ecoscope_workflows_ext_custom.tasks.localization import set_locale as set_locale
from ecoscope_workflows_ext_custom.tasks.results import (
    create_path_layer as create_path_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    view_state_from_layers as view_state_from_layers,
)
from ecoscope_workflows_ext_custom.tasks.skip import skip_to_none as skip_to_none
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_event_type_display_names_from_events as get_event_type_display_names_from_events,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrol_observations_from_patrols_df_and_combined_params as get_patrol_observations_from_patrols_df_and_combined_params,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrols_from_combined_params as get_patrols_from_combined_params,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_icf.tasks import (
    filter_patrols_by_ranger_name as filter_patrols_by_ranger_name,
)
from ecoscope_workflows_ext_icf.tasks import (
    filter_skip_sentinels as filter_skip_sentinels,
)
from ecoscope_workflows_ext_icf.tasks import format_coordinate as format_coordinate
from ecoscope_workflows_ext_icf.tasks import (
    generate_ranger_report as generate_ranger_report,
)
from ecoscope_workflows_ext_icf.tasks import get_eventnotes as get_eventnotes
from ecoscope_workflows_ext_icf.tasks import get_template_path as get_template_path
from ecoscope_workflows_ext_icf.tasks import get_user_me as get_user_me
from ecoscope_workflows_ext_icf.tasks import set_ranger_name as set_ranger_name
from ecoscope_workflows_ext_icf.tasks import to_crs as to_crs

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

user_details_params = dict()

# %%
# call the task


user_details = (
    get_user_me.set_task_instance_id("user_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(client=er_client_name, **user_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S", **time_range_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Define Base Maps

# %%
# parameters

base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


base_maps = (
    set_base_maps_pydeck.set_task_instance_id("base_maps")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_maps_params)
    .call()
)


# %% [markdown]
# ## Ranger Name

# %%
# parameters

ranger_name_params = dict(
    name=...,
)

# %%
# call the task


ranger_name = (
    set_ranger_name.set_task_instance_id("ranger_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**ranger_name_params)
    .call()
)


# %% [markdown]
# ## Set Locale

# %%
# parameters

locale_params = dict()

# %%
# call the task


locale = (
    set_locale.set_task_instance_id("locale")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(locale_str="es_ES.UTF-8", **locale_params)
    .call()
)


# %% [markdown]
# ## Set Template Path

# %%
# parameters

template_path_params = dict(
    template_path=...,
)

# %%
# call the task


template_path = (
    get_template_path.set_task_instance_id("template_path")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**template_path_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

patrol_and_events_params_params = dict(
    status=...,
    patrols_overlap_daterange=...,
)

# %%
# call the task


patrol_and_events_params = (
    set_patrols_and_patrol_events_params.set_task_instance_id(
        "patrol_and_events_params"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        patrol_types=[],
        event_types=[],
        sub_page_size=100,
        raise_on_empty=False,
        include_patrol_details=True,
        truncate_to_time_range=True,
        include_null_geometry=False,
        **patrol_and_events_params_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

prefetch_patrols_params = dict()

# %%
# call the task


prefetch_patrols = (
    get_patrols_from_combined_params.set_task_instance_id("prefetch_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(combined_params=patrol_and_events_params, **prefetch_patrols_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

ranger_filter_params = dict()

# %%
# call the task


ranger_filter = (
    filter_patrols_by_ranger_name.set_task_instance_id("ranger_filter")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=prefetch_patrols, name=ranger_name, **ranger_filter_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

patrol_observations_params = dict()

# %%
# call the task


patrol_observations = (
    get_patrol_observations_from_patrols_df_and_combined_params.set_task_instance_id(
        "patrol_observations"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        patrols_df=ranger_filter,
        combined_params=patrol_and_events_params,
        **patrol_observations_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

convert_patrols_to_user_timezone_params = dict()

# %%
# call the task


convert_patrols_to_user_timezone = (
    convert_values_to_timezone.set_task_instance_id("convert_patrols_to_user_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_observations,
        timezone=get_timezone,
        columns=["patrol_start_time", "patrol_end_time", "fixtime"],
        **convert_patrols_to_user_timezone_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

patrol_events_params = dict()

# %%
# call the task


patrol_events = (
    unpack_events_from_patrols_df_and_combined_params.set_task_instance_id(
        "patrol_events"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        patrols_df=ranger_filter,
        combined_params=patrol_and_events_params,
        **patrol_events_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

convert_events_to_user_tz_params = dict()

# %%
# call the task


convert_events_to_user_tz = (
    convert_values_to_timezone.set_task_instance_id("convert_events_to_user_tz")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_events,
        timezone=get_timezone,
        columns=["time"],
        **convert_events_to_user_tz_params,
    )
    .call()
)


# %% [markdown]
# ## Transform Observations to Relocations

# %%
# parameters

patrol_relocations_params = dict()

# %%
# call the task


patrol_relocations = (
    process_relocations.set_task_instance_id("patrol_relocations")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        observations=convert_patrols_to_user_timezone,
        relocs_columns=[
            "patrol_id",
            "patrol_start_time",
            "patrol_end_time",
            "patrol_type__display",
            "patrol_serial_number",
            "groupby_col",
            "fixtime",
            "junk_status",
            "geometry",
        ],
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **patrol_relocations_params,
    )
    .call()
)


# %% [markdown]
# ## Patrol Trajectory

# %%
# parameters

patrol_trajectory_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


patrol_trajectory = (
    relocations_to_trajectory.set_task_instance_id("patrol_trajectory")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocations=patrol_relocations, **patrol_trajectory_params)
    .call()
)


# %% [markdown]
# ## Calculate total Patrols

# %%
# parameters

total_patrols_params = dict()

# %%
# call the task


total_patrols = (
    dataframe_column_nunique.set_task_instance_id("total_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_trajectory, column_name="extra__patrol_id", **total_patrols_params
    )
    .call()
)


# %% [markdown]
# ## Create Single Value Widget for total Patrols

# %%
# parameters

total_patrols_sv_params = dict(
    view=...,
)

# %%
# call the task


total_patrols_sv = (
    create_single_value_widget_single_view.set_task_instance_id("total_patrols_sv")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Número Total",
        decimal_places=0,
        data=total_patrols,
        **total_patrols_sv_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate Total Distance

# %%
# parameters

total_distance_params = dict()

# %%
# call the task


total_distance = (
    dataframe_column_sum.set_task_instance_id("total_distance")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=patrol_trajectory, column_name="dist_meters", **total_distance_params)
    .call()
)


# %% [markdown]
# ## Convert total distance units

# %%
# parameters

total_distance_km_params = dict()

# %%
# call the task


total_distance_km = (
    with_unit.set_task_instance_id("total_distance_km")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        original_unit="m",
        new_unit="km",
        value=total_distance,
        **total_distance_km_params,
    )
    .call()
)


# %% [markdown]
# ## Create Single Value Widget for Total Distance

# %%
# parameters

total_distance_sv_params = dict(
    view=...,
)

# %%
# call the task


total_distance_sv = (
    create_single_value_widget_single_view.set_task_instance_id("total_distance_sv")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Distancia Total",
        decimal_places=2,
        data=total_distance_km,
        **total_distance_sv_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate Total Patrol Time

# %%
# parameters

total_patrol_time_params = dict()

# %%
# call the task


total_patrol_time = (
    dataframe_column_sum.set_task_instance_id("total_patrol_time")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="timespan_seconds", df=patrol_trajectory, **total_patrol_time_params
    )
    .call()
)


# %% [markdown]
# ## Convert total patrol time units

# %%
# parameters

total_patrol_time_hours_params = dict()

# %%
# call the task


total_patrol_time_hours = (
    with_unit.set_task_instance_id("total_patrol_time_hours")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        original_unit="s",
        new_unit="h",
        value=total_patrol_time,
        **total_patrol_time_hours_params,
    )
    .call()
)


# %% [markdown]
# ## Create Single Value Widgets for Total Patrol Time

# %%
# parameters

total_patrol_time_sv_params = dict(
    view=...,
)

# %%
# call the task


total_patrol_time_sv = (
    create_single_value_widget_single_view.set_task_instance_id("total_patrol_time_sv")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Horas Totales",
        decimal_places=1,
        data=total_patrol_time_hours,
        **total_patrol_time_sv_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate Total Events

# %%
# parameters

total_events_params = dict()

# %%
# call the task


total_events = (
    dataframe_count.set_task_instance_id("total_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=convert_events_to_user_tz, **total_events_params)
    .call()
)


# %% [markdown]
# ## Create Single Value Widget for Total Events

# %%
# parameters

total_events_sv_params = dict(
    view=...,
)

# %%
# call the task


total_events_sv = (
    create_single_value_widget_single_view.set_task_instance_id("total_events_sv")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Eventos Registrado",
        decimal_places=0,
        data=total_events,
        **total_events_sv_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize Patrols

# %%
# parameters

patrol_summary_table_params = dict()

# %%
# call the task


patrol_summary_table = (
    summarize_df.set_task_instance_id("patrol_summary_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_trajectory,
        groupby_cols=["extra__patrol_serial_number", "extra__patrol_type__display"],
        reset_index=True,
        summary_params=[
            {
                "display_name": "Inicio",
                "aggregator": "min",
                "column": "segment_start",
                "decimal_places": None,
            },
            {
                "display_name": "Fin",
                "aggregator": "max",
                "column": "segment_end",
                "decimal_places": None,
            },
            {
                "display_name": "Distancia (km)",
                "aggregator": "sum",
                "column": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
                "decimal_places": 2,
            },
            {
                "display_name": "Tiempo (hr)",
                "aggregator": "sum",
                "column": "timespan_seconds",
                "original_unit": "s",
                "new_unit": "h",
                "decimal_places": 2,
            },
        ],
        **patrol_summary_table_params,
    )
    .call()
)


# %% [markdown]
# ## Format Patrol Table

# %%
# parameters

formatted_patrol_table_params = dict()

# %%
# call the task


formatted_patrol_table = (
    map_columns.set_task_instance_id("formatted_patrol_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_summary_table,
        drop_columns=None,
        raise_if_not_found=True,
        retain_columns=[
            "extra__patrol_serial_number",
            "Inicio",
            "Fin",
            "extra__patrol_type__display",
            "Distancia (km)",
            "Tiempo (hr)",
        ],
        rename_columns={
            "extra__patrol_serial_number": "ID de la Patrulla",
            "extra__patrol_type__display": "Tipo de Patrulla",
        },
        **formatted_patrol_table_params,
    )
    .call()
)


# %% [markdown]
# ## Patrol Summary Table

# %%
# parameters

patrol_summary_html_table_params = dict(
    columns=...,
    table_config=...,
)

# %%
# call the task


patrol_summary_html_table = (
    draw_table.set_task_instance_id("patrol_summary_html_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=formatted_patrol_table,
        widget_id="patrol_summary_table_widget",
        **patrol_summary_html_table_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Patrol Summary HTML Table

# %%
# parameters

persist_patrol_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_patrol_html = (
    persist_text.set_task_instance_id("persist_patrol_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=patrol_summary_html_table,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="patrol_summary_table",
        **persist_patrol_html_params,
    )
    .call()
)


# %% [markdown]
# ## Create Patrol Summary Table Widget

# %%
# parameters

patrol_summary_table_widget_params = dict(
    view=...,
)

# %%
# call the task


patrol_summary_table_widget = (
    create_plot_widget_single_view.set_task_instance_id("patrol_summary_table_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Patrol Summary",
        data=persist_patrol_html,
        **patrol_summary_table_widget_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

event_type_display_names_params = dict()

# %%
# call the task


event_type_display_names = (
    get_event_type_display_names_from_events.set_task_instance_id(
        "event_type_display_names"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        events_gdf=convert_events_to_user_tz,
        append_category_names="never",
        **event_type_display_names_params,
    )
    .call()
)


# %% [markdown]
# ## Format Event Coordinates

# %%
# parameters

format_event_coords_params = dict()

# %%
# call the task


format_event_coords = (
    format_coordinate.set_task_instance_id("format_event_coords")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(events=event_type_display_names, **format_event_coords_params)
    .call()
)


# %% [markdown]
# ## Format Event Table

# %%
# parameters

formatted_event_table_params = dict()

# %%
# call the task


formatted_event_table = (
    map_columns.set_task_instance_id("formatted_event_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=format_event_coords,
        drop_columns=None,
        raise_if_not_found=True,
        retain_columns=["serial_number", "event_type_display", "coordinates", "time"],
        rename_columns={
            "serial_number": "ID del Evento",
            "event_type_display": "Tipo de Evento",
            "coordinates": "Coordenadas",
            "time": "Fecha",
        },
        **formatted_event_table_params,
    )
    .call()
)


# %% [markdown]
# ## Event Summary Table

# %%
# parameters

event_summary_html_table_params = dict(
    columns=...,
    table_config=...,
)

# %%
# call the task


event_summary_html_table = (
    draw_table.set_task_instance_id("event_summary_html_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=formatted_event_table,
        widget_id="event_summary_table_widget",
        **event_summary_html_table_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Event Summary HTML Table

# %%
# parameters

persist_event_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_event_html = (
    persist_text.set_task_instance_id("persist_event_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=event_summary_html_table,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="event_summary_table",
        **persist_event_html_params,
    )
    .call()
)


# %% [markdown]
# ## Create Event Summary Table Widget

# %%
# parameters

event_summary_table_widget_params = dict(
    view=...,
)

# %%
# call the task


event_summary_table_widget = (
    create_plot_widget_single_view.set_task_instance_id("event_summary_table_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Event Summary",
        data=persist_event_html,
        **event_summary_table_widget_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

spatial_features_params = dict(
    source=...,
    group_by=...,
    legend_title=...,
)

# %%
# call the task


spatial_features = (
    get_spatial_features.set_task_instance_id("spatial_features")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(client=er_client_name, **spatial_features_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

spatial_features_layer_params = dict()

# %%
# call the task


spatial_features_layer = (
    create_spatial_features_layer.set_task_instance_id("spatial_features_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(geodataframe=spatial_features, **spatial_features_layer_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

local_spatial_file_params = dict(
    file_path=...,
    layer=...,
    group_by=...,
    legend_title=...,
    style=...,
)

# %%
# call the task


local_spatial_file = (
    load_local_spatial_file.set_task_instance_id("local_spatial_file")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(**local_spatial_file_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

local_spatial_features_layer_params = dict()

# %%
# call the task


local_spatial_features_layer = (
    create_spatial_features_layer.set_task_instance_id("local_spatial_features_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(geodataframe=local_spatial_file, **local_spatial_features_layer_params)
    .call()
)


# %% [markdown]
# ## Apply Color to Patrols

# %%
# parameters

patrol_colormap_params = dict()

# %%
# call the task


patrol_colormap = (
    apply_color_map.set_task_instance_id("patrol_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_trajectory,
        input_column_name="extra__patrol_type__display",
        output_column_name="patrol_color",
        colormap="Paired",
        **patrol_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Reproject Patrols to WGS84

# %%
# parameters

patrol_colormap_wgs84_params = dict()

# %%
# call the task


patrol_colormap_wgs84 = (
    to_crs.set_task_instance_id("patrol_colormap_wgs84")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=patrol_colormap, crs="EPSG:4326", **patrol_colormap_wgs84_params
    )
    .call()
)


# %% [markdown]
# ## Create Patrol Tracks Layer

# %%
# parameters

patrol_tracks_layer_params = dict()

# %%
# call the task


patrol_tracks_layer = (
    create_path_layer.set_task_instance_id("patrol_tracks_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=patrol_colormap_wgs84,
        layer_style={
            "get_color": "patrol_color",
            "get_width": 3,
            "width_units": "pixels",
            "cap_rounded": True,
        },
        legend={
            "label_column": "extra__patrol_type__display",
            "color_column": "patrol_color",
        },
        data_url=None,
        **patrol_tracks_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Patrol Tracks Map View State

# %%
# parameters

patrol_map_view_state_params = dict(
    max_zoom=...,
)

# %%
# call the task


patrol_map_view_state = (
    view_state_from_layers.set_task_instance_id("patrol_map_view_state")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(layers=[patrol_tracks_layer], **patrol_map_view_state_params)
    .call()
)


# %% [markdown]
# ## Collect Patrol Map Layers

# %%
# parameters

patrol_map_layers_params = dict()

# %%
# call the task


patrol_map_layers = (
    filter_skip_sentinels.set_task_instance_id("patrol_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        iterables=[
            [spatial_features_layer],
            [local_spatial_features_layer],
            [patrol_tracks_layer],
        ],
        **patrol_map_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Patrol Tracks Map

# %%
# parameters

patrol_tracks_map_params = dict(
    widget_id=...,
)

# %%
# call the task


patrol_tracks_map = (
    draw_map.set_task_instance_id("patrol_tracks_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=patrol_map_layers,
        tile_layers=base_maps,
        static=False,
        title=None,
        max_zoom=17,
        view_state=patrol_map_view_state,
        legend_style={"placement": "bottom-right"},
        **patrol_tracks_map_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Patrol Tracks Map

# %%
# parameters

persist_patrol_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_patrol_map = (
    persist_text.set_task_instance_id("persist_patrol_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=patrol_tracks_map,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix=None,
        **persist_patrol_map_params,
    )
    .call()
)


# %% [markdown]
# ## Convert Patrol Tracks Map to PNG

# %%
# parameters

patrol_map_to_png_params = dict()

# %%
# call the task


patrol_map_to_png = (
    html_to_png.set_task_instance_id("patrol_map_to_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        html_path=persist_patrol_map,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"full_page": False},
        **patrol_map_to_png_params,
    )
    .call()
)


# %% [markdown]
# ## Create Patrol Tracks Map Widget

# %%
# parameters

patrol_tracks_map_widget_params = dict(
    view=...,
)

# %%
# call the task


patrol_tracks_map_widget = (
    create_map_widget_single_view.set_task_instance_id("patrol_tracks_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Patrol Tracks Map",
        data=persist_patrol_map,
        **patrol_tracks_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Color to Events

# %%
# parameters

event_colormap_params = dict()

# %%
# call the task


event_colormap = (
    apply_color_map.set_task_instance_id("event_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=event_type_display_names,
        input_column_name="event_type_display",
        output_column_name="event_color",
        colormap="Accent",
        **event_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Reproject Events to WGS84

# %%
# parameters

event_colormap_wgs84_params = dict()

# %%
# call the task


event_colormap_wgs84 = (
    to_crs.set_task_instance_id("event_colormap_wgs84")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=event_colormap, crs="EPSG:4326", **event_colormap_wgs84_params
    )
    .call()
)


# %% [markdown]
# ## Create Event Layer

# %%
# parameters

event_layer_params = dict()

# %%
# call the task


event_layer = (
    create_scatterplot_layer.set_task_instance_id("event_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=event_colormap_wgs84,
        layer_style={
            "get_fill_color": "event_color",
            "get_radius": 5,
            "radius_units": "pixels",
        },
        legend={"label_column": "event_type_display", "color_column": "event_color"},
        data_url=None,
        **event_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Event Scatterplot Map View State

# %%
# parameters

event_map_view_state_params = dict(
    max_zoom=...,
)

# %%
# call the task


event_map_view_state = (
    view_state_from_layers.set_task_instance_id("event_map_view_state")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(layers=[event_layer], **event_map_view_state_params)
    .call()
)


# %% [markdown]
# ## Collect Event Map Layers

# %%
# parameters

event_map_layers_params = dict()

# %%
# call the task


event_map_layers = (
    filter_skip_sentinels.set_task_instance_id("event_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        iterables=[
            [spatial_features_layer],
            [local_spatial_features_layer],
            [event_layer],
        ],
        **event_map_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Event Scatterplot Map

# %%
# parameters

event_scatterplot_map_params = dict(
    widget_id=...,
)

# %%
# call the task


event_scatterplot_map = (
    draw_map.set_task_instance_id("event_scatterplot_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=event_map_layers,
        tile_layers=base_maps,
        static=False,
        title=None,
        max_zoom=17,
        view_state=event_map_view_state,
        legend_style={"placement": "bottom-right"},
        **event_scatterplot_map_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Event Scatterplot Map

# %%
# parameters

persist_event_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_event_map = (
    persist_text.set_task_instance_id("persist_event_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=event_scatterplot_map,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix=None,
        **persist_event_map_params,
    )
    .call()
)


# %% [markdown]
# ## Convert Event Scatterplot Map to PNG

# %%
# parameters

event_map_to_png_params = dict()

# %%
# call the task


event_map_to_png = (
    html_to_png.set_task_instance_id("event_map_to_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        html_path=persist_event_map,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"full_page": False},
        **event_map_to_png_params,
    )
    .call()
)


# %% [markdown]
# ## Create Event Scatterplot Map Widget

# %%
# parameters

event_scatterplot_map_widget_params = dict(
    view=...,
)

# %%
# call the task


event_scatterplot_map_widget = (
    create_map_widget_single_view.set_task_instance_id("event_scatterplot_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Event Scatterplot Map",
        data=persist_event_map,
        **event_scatterplot_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

event_notes_params = dict()

# %%
# call the task


event_notes = (
    get_eventnotes.set_task_instance_id("event_notes")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        event=format_event_coords,
        client=er_client_name,
        use_index_as_id=False,
        **event_notes_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

event_subset_params = dict()

# %%
# call the task


event_subset = (
    select_columns.set_task_instance_id("event_subset")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=format_event_coords,
        raise_on_missing=False,
        columns=["id", "serial_number", "event_type_display"],
        **event_subset_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

eventnotes_add_event_serial_no_params = dict()

# %%
# call the task


eventnotes_add_event_serial_no = (
    merge_two_dataframes.set_task_instance_id("eventnotes_add_event_serial_no")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        left=event_notes,
        right=event_subset,
        on=None,
        how="left",
        left_on="event",
        right_on="id",
        left_index=False,
        right_index=False,
        fillna_value=None,
        **eventnotes_add_event_serial_no_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

safe_notes_params = dict()

# %%
# call the task


safe_notes = (
    skip_to_none.set_task_instance_id("safe_notes")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(df=eventnotes_add_event_serial_no, **safe_notes_params)
    .call()
)


# %% [markdown]
# ## Download Attachments

# %%
# parameters

download_attachments_params = dict(
    attachments_subdir=...,
    skip_download=...,
)

# %%
# call the task


download_attachments = (
    download_event_attachments.set_task_instance_id("download_attachments")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        event_gdf=format_event_coords,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        use_index_as_id=False,
        **download_attachments_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

norm_template_path_params = dict()

# %%
# call the task


norm_template_path = (
    remove_file_scheme.set_task_instance_id("norm_template_path")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(path=template_path, **norm_template_path_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

norm_output_dir_params = dict()

# %%
# call the task


norm_output_dir = (
    remove_file_scheme.set_task_instance_id("norm_output_dir")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **norm_output_dir_params)
    .call()
)


# %% [markdown]
# ## Generate Ranger Report

# %%
# parameters

generate_report_params = dict(
    include_attachment=...,
)

# %%
# call the task


generate_report = (
    generate_ranger_report.set_task_instance_id("generate_report")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        user_details=user_details,
        template_path=norm_template_path,
        output_dir=norm_output_dir,
        ranger_name=ranger_name,
        time_range=time_range,
        stats={
            "total_patrols": total_patrols,
            "total_distance": total_distance_km,
            "total_time": total_patrol_time_hours,
            "total_events": total_events,
        },
        patrol_summary=formatted_patrol_table,
        event_summary=formatted_event_table,
        patrol_map_path=patrol_map_to_png,
        event_map_path=event_map_to_png,
        events=format_event_coords,
        notes=safe_notes,
        attachments=download_attachments,
        **generate_report_params,
    )
    .call()
)


# %% [markdown]
# ## Dashboard

# %%
# parameters

template_dashboard_params = dict(
    groupers=...,
    warning=...,
)

# %%
# call the task


template_dashboard = (
    gather_dashboard.set_task_instance_id("template_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[
            total_patrols_sv,
            total_distance_sv,
            total_patrol_time_sv,
            total_events_sv,
            patrol_summary_table_widget,
            event_summary_table_widget,
            patrol_tracks_map_widget,
            event_scatterplot_map_widget,
        ],
        time_range=time_range,
        **template_dashboard_params,
    )
    .call()
)
