# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.localization import set_locale as set_locale
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope_workflows_ext_icf.tasks import get_template_path as get_template_path
from ecoscope_workflows_ext_icf.tasks import get_user_me as get_user_me
from ecoscope_workflows_ext_icf.tasks import set_ranger_name as set_ranger_name

get_patrols_from_combined_params = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_patrols_from_combined_params",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_icf.tasks import (
    filter_patrols_by_ranger_name as filter_patrols_by_ranger_name,
)

get_patrol_observations_from_patrols_df_and_combined_params = (
    create_task_magicmock(  # 🧪
        anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
        func_name="get_patrol_observations_from_patrols_df_and_combined_params",  # 🧪
    )
)  # 🧪
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table

get_event_type_display_names_from_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_event_type_display_names_from_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.results import (
    create_path_layer as create_path_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.skip import skip_to_none as skip_to_none
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_icf.tasks import format_coordinate as format_coordinate
from ecoscope_workflows_ext_icf.tasks import get_eventnotes as get_eventnotes
from ecoscope_workflows_ext_icf.tasks import to_crs as to_crs

download_event_attachments = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="download_event_attachments",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)
from ecoscope_workflows_ext_icf.tasks import (
    generate_ranger_report as generate_ranger_report,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "er_client_name": [],
        "user_details": ["er_client_name"],
        "time_range": [],
        "get_timezone": ["time_range"],
        "base_maps": [],
        "ranger_name": [],
        "locale": [],
        "template_path": [],
        "patrol_and_events_params": ["er_client_name", "time_range"],
        "prefetch_patrols": ["patrol_and_events_params"],
        "ranger_filter": ["prefetch_patrols", "ranger_name"],
        "patrol_observations": ["ranger_filter", "patrol_and_events_params"],
        "convert_patrols_to_user_timezone": ["patrol_observations", "get_timezone"],
        "patrol_events": ["ranger_filter", "patrol_and_events_params"],
        "convert_events_to_user_tz": ["patrol_events", "get_timezone"],
        "patrol_relocations": ["convert_patrols_to_user_timezone"],
        "patrol_trajectory": ["patrol_relocations"],
        "total_patrols": ["patrol_trajectory"],
        "total_patrols_sv": ["total_patrols"],
        "total_distance": ["patrol_trajectory"],
        "total_distance_km": ["total_distance"],
        "total_distance_sv": ["total_distance_km"],
        "total_patrol_time": ["patrol_trajectory"],
        "total_patrol_time_hours": ["total_patrol_time"],
        "total_patrol_time_sv": ["total_patrol_time_hours"],
        "total_events": ["convert_events_to_user_tz"],
        "total_events_sv": ["total_events"],
        "patrol_summary_table": ["patrol_trajectory"],
        "formatted_patrol_table": ["patrol_summary_table"],
        "patrol_summary_html_table": ["formatted_patrol_table"],
        "persist_patrol_html": ["patrol_summary_html_table"],
        "patrol_summary_table_widget": ["persist_patrol_html"],
        "event_type_display_names": ["er_client_name", "convert_events_to_user_tz"],
        "format_event_coords": ["event_type_display_names"],
        "formatted_event_table": ["format_event_coords"],
        "event_summary_html_table": ["formatted_event_table"],
        "persist_event_html": ["event_summary_html_table"],
        "event_summary_table_widget": ["persist_event_html"],
        "patrol_colormap": ["patrol_trajectory"],
        "patrol_colormap_wgs84": ["patrol_colormap"],
        "patrol_tracks_layer": ["patrol_colormap_wgs84"],
        "patrol_tracks_map": ["patrol_tracks_layer", "base_maps"],
        "persist_patrol_map": ["patrol_tracks_map"],
        "patrol_map_to_png": ["persist_patrol_map"],
        "patrol_tracks_map_widget": ["persist_patrol_map"],
        "event_colormap": ["event_type_display_names"],
        "event_colormap_wgs84": ["event_colormap"],
        "event_layer": ["event_colormap_wgs84"],
        "event_scatterplot_map": ["event_layer", "base_maps"],
        "persist_event_map": ["event_scatterplot_map"],
        "event_map_to_png": ["persist_event_map"],
        "event_scatterplot_map_widget": ["persist_event_map"],
        "event_notes": ["format_event_coords", "er_client_name"],
        "event_subset": ["format_event_coords"],
        "eventnotes_add_event_serial_no": ["event_notes", "event_subset"],
        "safe_notes": ["eventnotes_add_event_serial_no"],
        "download_attachments": ["er_client_name", "format_event_coords"],
        "norm_template_path": ["template_path"],
        "norm_output_dir": [],
        "generate_report": [
            "user_details",
            "norm_template_path",
            "norm_output_dir",
            "ranger_name",
            "time_range",
            "total_patrols",
            "total_distance_km",
            "total_patrol_time_hours",
            "total_events",
            "formatted_patrol_table",
            "formatted_event_table",
            "patrol_map_to_png",
            "event_map_to_png",
            "format_event_coords",
            "safe_notes",
            "download_attachments",
        ],
        "template_dashboard": [
            "workflow_details",
            "total_patrols_sv",
            "total_distance_sv",
            "total_patrol_time_sv",
            "total_events_sv",
            "patrol_summary_table_widget",
            "event_summary_table_widget",
            "patrol_tracks_map_widget",
            "event_scatterplot_map_widget",
            "time_range",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "user_details": Node(
            async_task=get_user_me.validate()
            .set_task_instance_id("user_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
            }
            | (params_dict.get("user_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "base_maps": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("base_maps")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_maps") or {}),
            method="call",
        ),
        "ranger_name": Node(
            async_task=set_ranger_name.validate()
            .set_task_instance_id("ranger_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("ranger_name") or {}),
            method="call",
        ),
        "locale": Node(
            async_task=set_locale.validate()
            .set_task_instance_id("locale")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "locale_str": "es_ES.UTF-8",
            }
            | (params_dict.get("locale") or {}),
            method="call",
        ),
        "template_path": Node(
            async_task=get_template_path.validate()
            .set_task_instance_id("template_path")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("template_path") or {}),
            method="call",
        ),
        "patrol_and_events_params": Node(
            async_task=set_patrols_and_patrol_events_params.validate()
            .set_task_instance_id("patrol_and_events_params")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "sub_page_size": 100,
                "raise_on_empty": False,
                "include_patrol_details": True,
                "truncate_to_time_range": True,
                "include_null_geometry": False,
            }
            | (params_dict.get("patrol_and_events_params") or {}),
            method="call",
        ),
        "prefetch_patrols": Node(
            async_task=get_patrols_from_combined_params.validate()
            .set_task_instance_id("prefetch_patrols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "combined_params": DependsOn("patrol_and_events_params"),
            }
            | (params_dict.get("prefetch_patrols") or {}),
            method="call",
        ),
        "ranger_filter": Node(
            async_task=filter_patrols_by_ranger_name.validate()
            .set_task_instance_id("ranger_filter")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("prefetch_patrols"),
                "name": DependsOn("ranger_name"),
            }
            | (params_dict.get("ranger_filter") or {}),
            method="call",
        ),
        "patrol_observations": Node(
            async_task=get_patrol_observations_from_patrols_df_and_combined_params.validate()
            .set_task_instance_id("patrol_observations")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "patrols_df": DependsOn("ranger_filter"),
                "combined_params": DependsOn("patrol_and_events_params"),
            }
            | (params_dict.get("patrol_observations") or {}),
            method="call",
        ),
        "convert_patrols_to_user_timezone": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_patrols_to_user_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_observations"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "patrol_start_time",
                    "patrol_end_time",
                    "fixtime",
                ],
            }
            | (params_dict.get("convert_patrols_to_user_timezone") or {}),
            method="call",
        ),
        "patrol_events": Node(
            async_task=unpack_events_from_patrols_df_and_combined_params.validate()
            .set_task_instance_id("patrol_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "patrols_df": DependsOn("ranger_filter"),
                "combined_params": DependsOn("patrol_and_events_params"),
            }
            | (params_dict.get("patrol_events") or {}),
            method="call",
        ),
        "convert_events_to_user_tz": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_events_to_user_tz")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_events"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "time",
                ],
            }
            | (params_dict.get("convert_events_to_user_tz") or {}),
            method="call",
        ),
        "patrol_relocations": Node(
            async_task=process_relocations.validate()
            .set_task_instance_id("patrol_relocations")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "observations": DependsOn("convert_patrols_to_user_timezone"),
                "relocs_columns": [
                    "patrol_id",
                    "patrol_start_time",
                    "patrol_end_time",
                    "patrol_type__display",
                    "patrol_serial_number",
                    "groupby_col",
                    "fixtime",
                    "junk_status",
                    "geometry",
                ],
                "filter_point_coords": [
                    {
                        "x": 180.0,
                        "y": 90.0,
                    },
                    {
                        "x": 0.0,
                        "y": 0.0,
                    },
                    {
                        "x": 1.0,
                        "y": 1.0,
                    },
                ],
            }
            | (params_dict.get("patrol_relocations") or {}),
            method="call",
        ),
        "patrol_trajectory": Node(
            async_task=relocations_to_trajectory.validate()
            .set_task_instance_id("patrol_trajectory")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("patrol_relocations"),
            }
            | (params_dict.get("patrol_trajectory") or {}),
            method="call",
        ),
        "total_patrols": Node(
            async_task=dataframe_column_nunique.validate()
            .set_task_instance_id("total_patrols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_trajectory"),
                "column_name": "extra__patrol_id",
            }
            | (params_dict.get("total_patrols") or {}),
            method="call",
        ),
        "total_patrols_sv": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_patrols_sv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Número Total",
                "decimal_places": 0,
                "data": DependsOn("total_patrols"),
            }
            | (params_dict.get("total_patrols_sv") or {}),
            method="call",
        ),
        "total_distance": Node(
            async_task=dataframe_column_sum.validate()
            .set_task_instance_id("total_distance")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_trajectory"),
                "column_name": "dist_meters",
            }
            | (params_dict.get("total_distance") or {}),
            method="call",
        ),
        "total_distance_km": Node(
            async_task=with_unit.validate()
            .set_task_instance_id("total_distance_km")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "original_unit": "m",
                "new_unit": "km",
                "value": DependsOn("total_distance"),
            }
            | (params_dict.get("total_distance_km") or {}),
            method="call",
        ),
        "total_distance_sv": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_distance_sv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Distancia Total",
                "decimal_places": 2,
                "data": DependsOn("total_distance_km"),
            }
            | (params_dict.get("total_distance_sv") or {}),
            method="call",
        ),
        "total_patrol_time": Node(
            async_task=dataframe_column_sum.validate()
            .set_task_instance_id("total_patrol_time")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "timespan_seconds",
                "df": DependsOn("patrol_trajectory"),
            }
            | (params_dict.get("total_patrol_time") or {}),
            method="call",
        ),
        "total_patrol_time_hours": Node(
            async_task=with_unit.validate()
            .set_task_instance_id("total_patrol_time_hours")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "original_unit": "s",
                "new_unit": "h",
                "value": DependsOn("total_patrol_time"),
            }
            | (params_dict.get("total_patrol_time_hours") or {}),
            method="call",
        ),
        "total_patrol_time_sv": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_patrol_time_sv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Horas Totales",
                "decimal_places": 1,
                "data": DependsOn("total_patrol_time_hours"),
            }
            | (params_dict.get("total_patrol_time_sv") or {}),
            method="call",
        ),
        "total_events": Node(
            async_task=dataframe_count.validate()
            .set_task_instance_id("total_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_events_to_user_tz"),
            }
            | (params_dict.get("total_events") or {}),
            method="call",
        ),
        "total_events_sv": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_events_sv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Eventos Registrado",
                "decimal_places": 0,
                "data": DependsOn("total_events"),
            }
            | (params_dict.get("total_events_sv") or {}),
            method="call",
        ),
        "patrol_summary_table": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("patrol_summary_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_trajectory"),
                "groupby_cols": [
                    "extra__patrol_serial_number",
                    "extra__patrol_type__display",
                ],
                "reset_index": True,
                "summary_params": [
                    {
                        "display_name": "Inicio",
                        "aggregator": "min",
                        "column": "segment_start",
                        "decimal_places": None,
                    },
                    {
                        "display_name": "Fin",
                        "aggregator": "max",
                        "column": "segment_end",
                        "decimal_places": None,
                    },
                    {
                        "display_name": "Distancia (km)",
                        "aggregator": "sum",
                        "column": "dist_meters",
                        "original_unit": "m",
                        "new_unit": "km",
                        "decimal_places": 2,
                    },
                    {
                        "display_name": "Tiempo (hr)",
                        "aggregator": "sum",
                        "column": "timespan_seconds",
                        "original_unit": "s",
                        "new_unit": "h",
                        "decimal_places": 2,
                    },
                ],
            }
            | (params_dict.get("patrol_summary_table") or {}),
            method="call",
        ),
        "formatted_patrol_table": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("formatted_patrol_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_summary_table"),
                "drop_columns": None,
                "raise_if_not_found": True,
                "retain_columns": [
                    "extra__patrol_serial_number",
                    "Inicio",
                    "Fin",
                    "extra__patrol_type__display",
                    "Distancia (km)",
                    "Tiempo (hr)",
                ],
                "rename_columns": {
                    "extra__patrol_serial_number": "ID de la Patrulla",
                    "extra__patrol_type__display": "Tipo de Patrulla",
                },
            }
            | (params_dict.get("formatted_patrol_table") or {}),
            method="call",
        ),
        "patrol_summary_html_table": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("patrol_summary_html_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("formatted_patrol_table"),
                "widget_id": "patrol_summary_table_widget",
            }
            | (params_dict.get("patrol_summary_html_table") or {}),
            method="call",
        ),
        "persist_patrol_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_patrol_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("patrol_summary_html_table"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "patrol_summary_table",
            }
            | (params_dict.get("persist_patrol_html") or {}),
            method="call",
        ),
        "patrol_summary_table_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("patrol_summary_table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Patrol Summary",
                "data": DependsOn("persist_patrol_html"),
            }
            | (params_dict.get("patrol_summary_table_widget") or {}),
            method="call",
        ),
        "event_type_display_names": Node(
            async_task=get_event_type_display_names_from_events.validate()
            .set_task_instance_id("event_type_display_names")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "events_gdf": DependsOn("convert_events_to_user_tz"),
                "append_category_names": "never",
            }
            | (params_dict.get("event_type_display_names") or {}),
            method="call",
        ),
        "format_event_coords": Node(
            async_task=format_coordinate.validate()
            .set_task_instance_id("format_event_coords")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "events": DependsOn("event_type_display_names"),
            }
            | (params_dict.get("format_event_coords") or {}),
            method="call",
        ),
        "formatted_event_table": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("formatted_event_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("format_event_coords"),
                "drop_columns": None,
                "raise_if_not_found": True,
                "retain_columns": [
                    "serial_number",
                    "event_type_display",
                    "coordinates",
                    "time",
                ],
                "rename_columns": {
                    "serial_number": "ID del Evento",
                    "event_type_display": "Tipo de Evento",
                    "coordinates": "Coordenadas",
                    "time": "Fecha",
                },
            }
            | (params_dict.get("formatted_event_table") or {}),
            method="call",
        ),
        "event_summary_html_table": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("event_summary_html_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("formatted_event_table"),
                "widget_id": "event_summary_table_widget",
            }
            | (params_dict.get("event_summary_html_table") or {}),
            method="call",
        ),
        "persist_event_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_event_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("event_summary_html_table"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "event_summary_table",
            }
            | (params_dict.get("persist_event_html") or {}),
            method="call",
        ),
        "event_summary_table_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("event_summary_table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Event Summary",
                "data": DependsOn("persist_event_html"),
            }
            | (params_dict.get("event_summary_table_widget") or {}),
            method="call",
        ),
        "patrol_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("patrol_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_trajectory"),
                "input_column_name": "extra__patrol_type__display",
                "output_column_name": "patrol_color",
                "colormap": "Paired",
            }
            | (params_dict.get("patrol_colormap") or {}),
            method="call",
        ),
        "patrol_colormap_wgs84": Node(
            async_task=to_crs.validate()
            .set_task_instance_id("patrol_colormap_wgs84")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("patrol_colormap"),
                "crs": "EPSG:4326",
            }
            | (params_dict.get("patrol_colormap_wgs84") or {}),
            method="call",
        ),
        "patrol_tracks_layer": Node(
            async_task=create_path_layer.validate()
            .set_task_instance_id("patrol_tracks_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("patrol_colormap_wgs84"),
                "layer_style": {
                    "get_color": "patrol_color",
                    "get_width": 3,
                    "width_units": "pixels",
                    "cap_rounded": True,
                },
                "legend": {
                    "label_column": "extra__patrol_type__display",
                    "color_column": "patrol_color",
                },
                "data_url": None,
            }
            | (params_dict.get("patrol_tracks_layer") or {}),
            method="call",
        ),
        "patrol_tracks_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("patrol_tracks_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": DependsOn("patrol_tracks_layer"),
                "tile_layers": DependsOn("base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 17,
                "view_state": None,
                "legend_style": {
                    "placement": "bottom-right",
                },
            }
            | (params_dict.get("patrol_tracks_map") or {}),
            method="call",
        ),
        "persist_patrol_map": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_patrol_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("patrol_tracks_map"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": None,
            }
            | (params_dict.get("persist_patrol_map") or {}),
            method="call",
        ),
        "patrol_map_to_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("patrol_map_to_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "html_path": DependsOn("persist_patrol_map"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "config": {
                    "full_page": False,
                },
            }
            | (params_dict.get("patrol_map_to_png") or {}),
            method="call",
        ),
        "patrol_tracks_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("patrol_tracks_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Patrol Tracks Map",
                "data": DependsOn("persist_patrol_map"),
            }
            | (params_dict.get("patrol_tracks_map_widget") or {}),
            method="call",
        ),
        "event_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("event_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("event_type_display_names"),
                "input_column_name": "event_type_display",
                "output_column_name": "event_color",
                "colormap": "Accent",
            }
            | (params_dict.get("event_colormap") or {}),
            method="call",
        ),
        "event_colormap_wgs84": Node(
            async_task=to_crs.validate()
            .set_task_instance_id("event_colormap_wgs84")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("event_colormap"),
                "crs": "EPSG:4326",
            }
            | (params_dict.get("event_colormap_wgs84") or {}),
            method="call",
        ),
        "event_layer": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("event_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("event_colormap_wgs84"),
                "layer_style": {
                    "get_fill_color": "event_color",
                    "get_radius": 5,
                    "radius_units": "pixels",
                },
                "legend": {
                    "label_column": "event_type_display",
                    "color_column": "event_color",
                },
                "data_url": None,
            }
            | (params_dict.get("event_layer") or {}),
            method="call",
        ),
        "event_scatterplot_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("event_scatterplot_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": DependsOn("event_layer"),
                "tile_layers": DependsOn("base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 17,
                "view_state": None,
                "legend_style": {
                    "placement": "bottom-right",
                },
            }
            | (params_dict.get("event_scatterplot_map") or {}),
            method="call",
        ),
        "persist_event_map": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_event_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("event_scatterplot_map"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": None,
            }
            | (params_dict.get("persist_event_map") or {}),
            method="call",
        ),
        "event_map_to_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("event_map_to_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "html_path": DependsOn("persist_event_map"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "config": {
                    "full_page": False,
                },
            }
            | (params_dict.get("event_map_to_png") or {}),
            method="call",
        ),
        "event_scatterplot_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("event_scatterplot_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Event Scatterplot Map",
                "data": DependsOn("persist_event_map"),
            }
            | (params_dict.get("event_scatterplot_map_widget") or {}),
            method="call",
        ),
        "event_notes": Node(
            async_task=get_eventnotes.validate()
            .set_task_instance_id("event_notes")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "event": DependsOn("format_event_coords"),
                "client": DependsOn("er_client_name"),
                "use_index_as_id": False,
            }
            | (params_dict.get("event_notes") or {}),
            method="call",
        ),
        "event_subset": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("event_subset")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("format_event_coords"),
                "raise_on_missing": False,
                "columns": [
                    "id",
                    "serial_number",
                    "event_type_display",
                ],
            }
            | (params_dict.get("event_subset") or {}),
            method="call",
        ),
        "eventnotes_add_event_serial_no": Node(
            async_task=merge_two_dataframes.validate()
            .set_task_instance_id("eventnotes_add_event_serial_no")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "left": DependsOn("event_notes"),
                "right": DependsOn("event_subset"),
                "on": None,
                "how": "left",
                "left_on": "event",
                "right_on": "id",
                "left_index": False,
                "right_index": False,
                "fillna_value": None,
            }
            | (params_dict.get("eventnotes_add_event_serial_no") or {}),
            method="call",
        ),
        "safe_notes": Node(
            async_task=skip_to_none.validate()
            .set_task_instance_id("safe_notes")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("eventnotes_add_event_serial_no"),
            }
            | (params_dict.get("safe_notes") or {}),
            method="call",
        ),
        "download_attachments": Node(
            async_task=download_event_attachments.validate()
            .set_task_instance_id("download_attachments")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "event_gdf": DependsOn("format_event_coords"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "use_index_as_id": False,
            }
            | (params_dict.get("download_attachments") or {}),
            method="call",
        ),
        "norm_template_path": Node(
            async_task=remove_file_scheme.validate()
            .set_task_instance_id("norm_template_path")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "path": DependsOn("template_path"),
            }
            | (params_dict.get("norm_template_path") or {}),
            method="call",
        ),
        "norm_output_dir": Node(
            async_task=remove_file_scheme.validate()
            .set_task_instance_id("norm_output_dir")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("norm_output_dir") or {}),
            method="call",
        ),
        "generate_report": Node(
            async_task=generate_ranger_report.validate()
            .set_task_instance_id("generate_report")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "user_details": DependsOn("user_details"),
                "template_path": DependsOn("norm_template_path"),
                "output_dir": DependsOn("norm_output_dir"),
                "ranger_name": DependsOn("ranger_name"),
                "time_range": DependsOn("time_range"),
                "stats": {
                    "total_patrols": DependsOn("total_patrols"),
                    "total_distance": DependsOn("total_distance_km"),
                    "total_time": DependsOn("total_patrol_time_hours"),
                    "total_events": DependsOn("total_events"),
                },
                "patrol_summary": DependsOn("formatted_patrol_table"),
                "event_summary": DependsOn("formatted_event_table"),
                "patrol_map_path": DependsOn("patrol_map_to_png"),
                "event_map_path": DependsOn("event_map_to_png"),
                "events": DependsOn("format_event_coords"),
                "notes": DependsOn("safe_notes"),
                "attachments": DependsOn("download_attachments"),
            }
            | (params_dict.get("generate_report") or {}),
            method="call",
        ),
        "template_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("template_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("total_patrols_sv"),
                    DependsOn("total_distance_sv"),
                    DependsOn("total_patrol_time_sv"),
                    DependsOn("total_events_sv"),
                    DependsOn("patrol_summary_table_widget"),
                    DependsOn("event_summary_table_widget"),
                    DependsOn("patrol_tracks_map_widget"),
                    DependsOn("event_scatterplot_map_widget"),
                ],
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("template_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
