# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_apn.tasks import (
    add_fullscreen_to_map as add_fullscreen_to_map,
)
from ecoscope_workflows_ext_apn.tasks import (
    gather_apn_dashboard as gather_apn_dashboard,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    download_event_attachments as download_event_attachments,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)
from ecoscope_workflows_ext_custom.tasks.localization import set_locale as set_locale
from ecoscope_workflows_ext_custom.tasks.results import (
    create_path_layer as create_path_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    view_state_from_layers as view_state_from_layers,
)
from ecoscope_workflows_ext_custom.tasks.skip import skip_to_none as skip_to_none
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_event_type_display_names_from_events as get_event_type_display_names_from_events,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrol_observations_from_patrols_df_and_combined_params as get_patrol_observations_from_patrols_df_and_combined_params,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrols_from_combined_params as get_patrols_from_combined_params,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_icf.tasks import (
    filter_patrols_by_ranger_name as filter_patrols_by_ranger_name,
)
from ecoscope_workflows_ext_icf.tasks import (
    filter_skip_sentinels as filter_skip_sentinels,
)
from ecoscope_workflows_ext_icf.tasks import format_coordinate as format_coordinate
from ecoscope_workflows_ext_icf.tasks import (
    generate_ranger_report as generate_ranger_report,
)
from ecoscope_workflows_ext_icf.tasks import get_eventnotes as get_eventnotes_1
from ecoscope_workflows_ext_icf.tasks import get_template_path as get_template_path
from ecoscope_workflows_ext_icf.tasks import get_user_me as get_user_me_1
from ecoscope_workflows_ext_icf.tasks import set_ranger_name as set_ranger_name
from ecoscope_workflows_ext_icf.tasks import to_crs as to_crs

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    user_details = (
        get_user_me_1.validate()
        .set_task_instance_id("user_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client_name, **(params_dict.get("user_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    get_timezone = (
        get_timezone_from_time_range.validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params_dict.get("get_timezone") or {}))
        .call()
    )

    base_maps = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("base_maps") or {}))
        .call()
    )

    spatial_features = (
        get_spatial_features.validate()
        .set_task_instance_id("spatial_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client_name, **(params_dict.get("spatial_features") or {}))
        .call()
    )

    spatial_features_layer = (
        create_spatial_features_layer.validate()
        .set_task_instance_id("spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=spatial_features,
            **(params_dict.get("spatial_features_layer") or {}),
        )
        .call()
    )

    ranger_name = (
        set_ranger_name.validate()
        .set_task_instance_id("ranger_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("ranger_name") or {}))
        .call()
    )

    locale = (
        set_locale.validate()
        .set_task_instance_id("locale")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(locale_str="es_ES.UTF-8", **(params_dict.get("locale") or {}))
        .call()
    )

    template_path = (
        get_template_path.validate()
        .set_task_instance_id("template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("template_path") or {}))
        .call()
    )

    patrol_and_events_params = (
        set_patrols_and_patrol_events_params.validate()
        .set_task_instance_id("patrol_and_events_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            patrol_types=[],
            event_types=[],
            sub_page_size=100,
            raise_on_empty=False,
            include_patrol_details=True,
            truncate_to_time_range=True,
            include_null_geometry=False,
            **(params_dict.get("patrol_and_events_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        get_patrols_from_combined_params.validate()
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=patrol_and_events_params,
            **(params_dict.get("prefetch_patrols") or {}),
        )
        .call()
    )

    ranger_filter = (
        filter_patrols_by_ranger_name.validate()
        .set_task_instance_id("ranger_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=prefetch_patrols,
            name=ranger_name,
            **(params_dict.get("ranger_filter") or {}),
        )
        .call()
    )

    patrol_observations = (
        get_patrol_observations_from_patrols_df_and_combined_params.validate()
        .set_task_instance_id("patrol_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=ranger_filter,
            combined_params=patrol_and_events_params,
            **(params_dict.get("patrol_observations") or {}),
        )
        .call()
    )

    convert_patrols_to_user_timezone = (
        convert_values_to_timezone.validate()
        .set_task_instance_id("convert_patrols_to_user_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_observations,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params_dict.get("convert_patrols_to_user_timezone") or {}),
        )
        .call()
    )

    patrol_events = (
        unpack_events_from_patrols_df_and_combined_params.validate()
        .set_task_instance_id("patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=ranger_filter,
            combined_params=patrol_and_events_params,
            **(params_dict.get("patrol_events") or {}),
        )
        .call()
    )

    convert_events_to_user_tz = (
        convert_values_to_timezone.validate()
        .set_task_instance_id("convert_events_to_user_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_events,
            timezone=get_timezone,
            columns=["time"],
            **(params_dict.get("convert_events_to_user_tz") or {}),
        )
        .call()
    )

    patrol_relocations = (
        process_relocations.validate()
        .set_task_instance_id("patrol_relocations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_patrols_to_user_timezone,
            relocs_columns=[
                "patrol_id",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_type__display",
                "patrol_serial_number",
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params_dict.get("patrol_relocations") or {}),
        )
        .call()
    )

    patrol_trajectory = (
        relocations_to_trajectory.validate()
        .set_task_instance_id("patrol_trajectory")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=patrol_relocations,
            **(params_dict.get("patrol_trajectory") or {}),
        )
        .call()
    )

    total_patrols = (
        dataframe_column_nunique.validate()
        .set_task_instance_id("total_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_trajectory,
            column_name="extra__patrol_id",
            **(params_dict.get("total_patrols") or {}),
        )
        .call()
    )

    total_patrols_sv = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_patrols_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Número Total",
            decimal_places=0,
            data=total_patrols,
            **(params_dict.get("total_patrols_sv") or {}),
        )
        .call()
    )

    total_distance = (
        dataframe_column_sum.validate()
        .set_task_instance_id("total_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_trajectory,
            column_name="dist_meters",
            **(params_dict.get("total_distance") or {}),
        )
        .call()
    )

    total_distance_km = (
        with_unit.validate()
        .set_task_instance_id("total_distance_km")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="m",
            new_unit="km",
            value=total_distance,
            **(params_dict.get("total_distance_km") or {}),
        )
        .call()
    )

    total_distance_sv = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_distance_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Distancia Total",
            decimal_places=2,
            data=total_distance_km,
            **(params_dict.get("total_distance_sv") or {}),
        )
        .call()
    )

    total_patrol_time = (
        dataframe_column_sum.validate()
        .set_task_instance_id("total_patrol_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="timespan_seconds",
            df=patrol_trajectory,
            **(params_dict.get("total_patrol_time") or {}),
        )
        .call()
    )

    total_patrol_time_hours = (
        with_unit.validate()
        .set_task_instance_id("total_patrol_time_hours")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="s",
            new_unit="h",
            value=total_patrol_time,
            **(params_dict.get("total_patrol_time_hours") or {}),
        )
        .call()
    )

    total_patrol_time_sv = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_patrol_time_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Horas Totales",
            decimal_places=1,
            data=total_patrol_time_hours,
            **(params_dict.get("total_patrol_time_sv") or {}),
        )
        .call()
    )

    total_events = (
        dataframe_count.validate()
        .set_task_instance_id("total_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_to_user_tz, **(params_dict.get("total_events") or {})
        )
        .call()
    )

    total_events_sv = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_events_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Eventos Registrado",
            decimal_places=0,
            data=total_events,
            **(params_dict.get("total_events_sv") or {}),
        )
        .call()
    )

    patrol_summary_table = (
        summarize_df.validate()
        .set_task_instance_id("patrol_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_trajectory,
            groupby_cols=["extra__patrol_serial_number", "extra__patrol_type__display"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Inicio",
                    "aggregator": "min",
                    "column": "segment_start",
                    "decimal_places": None,
                },
                {
                    "display_name": "Fin",
                    "aggregator": "max",
                    "column": "segment_end",
                    "decimal_places": None,
                },
                {
                    "display_name": "Distancia (km)",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                    "decimal_places": 2,
                },
                {
                    "display_name": "Tiempo (hr)",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 2,
                },
            ],
            **(params_dict.get("patrol_summary_table") or {}),
        )
        .call()
    )

    formatted_patrol_table = (
        map_columns.validate()
        .set_task_instance_id("formatted_patrol_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_summary_table,
            drop_columns=None,
            raise_if_not_found=True,
            retain_columns=[
                "extra__patrol_serial_number",
                "Inicio",
                "Fin",
                "extra__patrol_type__display",
                "Distancia (km)",
                "Tiempo (hr)",
            ],
            rename_columns={
                "extra__patrol_serial_number": "ID de la Patrulla",
                "extra__patrol_type__display": "Tipo de Patrulla",
            },
            **(params_dict.get("formatted_patrol_table") or {}),
        )
        .call()
    )

    patrol_summary_html_table = (
        draw_table.validate()
        .set_task_instance_id("patrol_summary_html_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=formatted_patrol_table,
            widget_id="patrol_summary_table_widget",
            **(params_dict.get("patrol_summary_html_table") or {}),
        )
        .call()
    )

    persist_patrol_html = (
        persist_text.validate()
        .set_task_instance_id("persist_patrol_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=patrol_summary_html_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrol_summary_table",
            **(params_dict.get("persist_patrol_html") or {}),
        )
        .call()
    )

    patrol_summary_table_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("patrol_summary_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Summary",
            data=persist_patrol_html,
            **(params_dict.get("patrol_summary_table_widget") or {}),
        )
        .call()
    )

    event_type_display_names = (
        get_event_type_display_names_from_events.validate()
        .set_task_instance_id("event_type_display_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            events_gdf=convert_events_to_user_tz,
            append_category_names="never",
            **(params_dict.get("event_type_display_names") or {}),
        )
        .call()
    )

    format_event_coords = (
        format_coordinate.validate()
        .set_task_instance_id("format_event_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            events=event_type_display_names,
            **(params_dict.get("format_event_coords") or {}),
        )
        .call()
    )

    formatted_event_table = (
        map_columns.validate()
        .set_task_instance_id("formatted_event_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=format_event_coords,
            drop_columns=None,
            raise_if_not_found=True,
            retain_columns=[
                "serial_number",
                "event_type_display",
                "coordinates",
                "time",
            ],
            rename_columns={
                "serial_number": "ID del Evento",
                "event_type_display": "Tipo de Evento",
                "coordinates": "Coordenadas",
                "time": "Fecha",
            },
            **(params_dict.get("formatted_event_table") or {}),
        )
        .call()
    )

    event_summary_html_table = (
        draw_table.validate()
        .set_task_instance_id("event_summary_html_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=formatted_event_table,
            widget_id="event_summary_table_widget",
            **(params_dict.get("event_summary_html_table") or {}),
        )
        .call()
    )

    persist_event_html = (
        persist_text.validate()
        .set_task_instance_id("persist_event_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=event_summary_html_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="event_summary_table",
            **(params_dict.get("persist_event_html") or {}),
        )
        .call()
    )

    event_summary_table_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("event_summary_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Event Summary",
            data=persist_event_html,
            **(params_dict.get("event_summary_table_widget") or {}),
        )
        .call()
    )

    patrol_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("patrol_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_trajectory,
            input_column_name="extra__patrol_type__display",
            output_column_name="patrol_color",
            colormap="Paired",
            **(params_dict.get("patrol_colormap") or {}),
        )
        .call()
    )

    patrol_colormap_wgs84 = (
        to_crs.validate()
        .set_task_instance_id("patrol_colormap_wgs84")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=patrol_colormap,
            crs="EPSG:4326",
            **(params_dict.get("patrol_colormap_wgs84") or {}),
        )
        .call()
    )

    patrol_legend_title = (
        set_string_var.validate()
        .set_task_instance_id("patrol_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("patrol_legend_title") or {}))
        .call()
    )

    patrol_tracks_layer = (
        create_path_layer.validate()
        .set_task_instance_id("patrol_tracks_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=patrol_colormap_wgs84,
            layer_style={
                "get_color": "patrol_color",
                "get_width": 3,
                "width_units": "pixels",
                "cap_rounded": True,
            },
            legend={
                "title": patrol_legend_title,
                "label_column": "extra__patrol_type__display",
                "color_column": "patrol_color",
            },
            data_url=None,
            **(params_dict.get("patrol_tracks_layer") or {}),
        )
        .call()
    )

    event_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("event_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=event_type_display_names,
            input_column_name="event_type_display",
            output_column_name="event_color",
            colormap="Accent",
            **(params_dict.get("event_colormap") or {}),
        )
        .call()
    )

    event_colormap_wgs84 = (
        to_crs.validate()
        .set_task_instance_id("event_colormap_wgs84")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_colormap,
            crs="EPSG:4326",
            **(params_dict.get("event_colormap_wgs84") or {}),
        )
        .call()
    )

    event_legend_title = (
        set_string_var.validate()
        .set_task_instance_id("event_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("event_legend_title") or {}))
        .call()
    )

    event_layer = (
        create_scatterplot_layer.validate()
        .set_task_instance_id("event_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_colormap_wgs84,
            layer_style={
                "get_fill_color": "event_color",
                "get_radius": 5,
                "radius_units": "pixels",
            },
            legend={
                "title": event_legend_title,
                "label_column": "event_type_display",
                "color_column": "event_color",
            },
            data_url=None,
            **(params_dict.get("event_layer") or {}),
        )
        .call()
    )

    patrol_event_view_state = (
        view_state_from_layers.validate()
        .set_task_instance_id("patrol_event_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[patrol_tracks_layer, event_layer],
            max_zoom=17,
            **(params_dict.get("patrol_event_view_state") or {}),
        )
        .call()
    )

    patrol_event_map_layers = (
        filter_skip_sentinels.validate()
        .set_task_instance_id("patrol_event_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[[spatial_features_layer], [patrol_tracks_layer], [event_layer]],
            **(params_dict.get("patrol_event_map_layers") or {}),
        )
        .call()
    )

    patrol_event_map = (
        draw_map.validate()
        .set_task_instance_id("patrol_event_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=patrol_event_map_layers,
            tile_layers=base_maps,
            static=False,
            title=None,
            max_zoom=17,
            view_state=patrol_event_view_state,
            legend_style={"placement": "bottom-right"},
            **(params_dict.get("patrol_event_map") or {}),
        )
        .call()
    )

    patrol_event_map_fullscreen = (
        add_fullscreen_to_map.validate()
        .set_task_instance_id("patrol_event_map_fullscreen")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html=patrol_event_map,
            **(params_dict.get("patrol_event_map_fullscreen") or {}),
        )
        .call()
    )

    persist_patrol_event_map = (
        persist_text.validate()
        .set_task_instance_id("persist_patrol_event_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=patrol_event_map_fullscreen,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix=None,
            **(params_dict.get("persist_patrol_event_map") or {}),
        )
        .call()
    )

    patrol_event_map_to_png = (
        html_to_png.validate()
        .set_task_instance_id("patrol_event_map_to_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=persist_patrol_event_map,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"full_page": False},
            **(params_dict.get("patrol_event_map_to_png") or {}),
        )
        .call()
    )

    patrol_event_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("patrol_event_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol and Event Map",
            data=persist_patrol_event_map,
            **(params_dict.get("patrol_event_map_widget") or {}),
        )
        .call()
    )

    event_notes = (
        get_eventnotes_1.validate()
        .set_task_instance_id("event_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event=format_event_coords,
            client=er_client_name,
            use_index_as_id=False,
            **(params_dict.get("event_notes") or {}),
        )
        .call()
    )

    event_subset = (
        select_columns.validate()
        .set_task_instance_id("event_subset")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=format_event_coords,
            raise_on_missing=False,
            columns=["id", "serial_number", "event_type_display"],
            **(params_dict.get("event_subset") or {}),
        )
        .call()
    )

    eventnotes_add_event_serial_no = (
        merge_two_dataframes.validate()
        .set_task_instance_id("eventnotes_add_event_serial_no")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=event_notes,
            right=event_subset,
            on=None,
            how="left",
            left_on="event",
            right_on="id",
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params_dict.get("eventnotes_add_event_serial_no") or {}),
        )
        .call()
    )

    safe_notes = (
        skip_to_none.validate()
        .set_task_instance_id("safe_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=eventnotes_add_event_serial_no, **(params_dict.get("safe_notes") or {})
        )
        .call()
    )

    download_attachments = (
        download_event_attachments.validate()
        .set_task_instance_id("download_attachments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            event_gdf=format_event_coords,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            use_index_as_id=False,
            **(params_dict.get("download_attachments") or {}),
        )
        .call()
    )

    norm_template_path = (
        remove_file_scheme.validate()
        .set_task_instance_id("norm_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(path=template_path, **(params_dict.get("norm_template_path") or {}))
        .call()
    )

    norm_output_dir = (
        remove_file_scheme.validate()
        .set_task_instance_id("norm_output_dir")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("norm_output_dir") or {}),
        )
        .call()
    )

    generate_report = (
        generate_ranger_report.validate()
        .set_task_instance_id("generate_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            user_details=user_details,
            template_path=norm_template_path,
            output_dir=norm_output_dir,
            ranger_name=ranger_name,
            time_range=time_range,
            stats={
                "total_patrols": total_patrols,
                "total_distance": total_distance_km,
                "total_time": total_patrol_time_hours,
                "total_events": total_events,
            },
            patrol_summary=formatted_patrol_table,
            event_summary=formatted_event_table,
            patrol_map_path=patrol_event_map_to_png,
            event_map_path=patrol_event_map_to_png,
            events=format_event_coords,
            notes=safe_notes,
            attachments=download_attachments,
            **(params_dict.get("generate_report") or {}),
        )
        .call()
    )

    template_dashboard = (
        gather_apn_dashboard.validate()
        .set_task_instance_id("template_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_patrols_sv,
                total_distance_sv,
                total_patrol_time_sv,
                total_events_sv,
                patrol_summary_table_widget,
                event_summary_table_widget,
                patrol_event_map_widget,
            ],
            time_range=time_range,
            **(params_dict.get("template_dashboard") or {}),
        )
        .call()
    )

    return template_dashboard
