# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps1(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps6(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps7(BaseModel):
    url: Optional[
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
    ] = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: Optional[int] = Field(
        20,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: Optional[int] = Field(
        0,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMaps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: Optional[
        List[
            Union[
                BaseMaps1,
                BaseMaps2,
                BaseMaps3,
                BaseMaps4,
                BaseMaps5,
                BaseMaps6,
                BaseMaps7,
            ]
        ]
    ] = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
                "max_zoom": 20,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
                "max_zoom": 20,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class RangerName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Name of the ranger.", title="Name")


class TemplatePath(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ..., description="Path to the DOCX template file.", title="Template Path"
    )


class StatusEnum(str, Enum):
    active = "active"
    overdue = "overdue"
    done = "done"
    cancelled = "cancelled"


class PatrolAndEventsParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Optional[List[StatusEnum]] = Field(
        ["done"],
        description="Choose to analyze patrols with a certain status. If left empty, patrols of all status will be analyzed",
        title="Patrol Status",
    )
    patrols_overlap_daterange: Optional[bool] = Field(
        True,
        description="Whether or not to include patrols that start or end outside of the time range",
        title="Patrols Overlap Daterange",
    )


class PatrolAndEventTypes(BaseModel):
    patrol_and_events_params: Optional[PatrolAndEventsParams] = Field(None, title="")


class TableConfig(BaseModel):
    enable_sorting: Optional[bool] = Field(True, title="Enable Sorting")
    enable_filtering: Optional[bool] = Field(False, title="Enable Filtering")
    enable_download: Optional[bool] = Field(False, title="Enable Download")
    hide_header: Optional[bool] = Field(False, title="Hide Header")


class PatrolSummaryHtmlTable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    columns: Optional[List[str]] = Field(
        None,
        description="The list of dataframe columns to render in the table. Leave empty to render all columns",
        title="Columns",
    )
    table_config: Optional[TableConfig] = Field(
        None, description="Configuration options for the table.", title="Table Config"
    )


class PatrolSummaryTable(BaseModel):
    patrol_summary_html_table: Optional[PatrolSummaryHtmlTable] = Field(None, title="")


class EventSummaryHtmlTable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    columns: Optional[List[str]] = Field(
        None,
        description="The list of dataframe columns to render in the table. Leave empty to render all columns",
        title="Columns",
    )
    table_config: Optional[TableConfig] = Field(
        None, description="Configuration options for the table.", title="Table Config"
    )


class EventSummaryTable(BaseModel):
    event_summary_html_table: Optional[EventSummaryHtmlTable] = Field(None, title="")


class DownloadAttachments(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attachments_subdir: Optional[str] = Field(
        "attachments",
        description="Subdirectory inside the output directory to store attachments.",
        title="Attachments Subdirectory",
    )
    skip_download: Optional[bool] = Field(
        False,
        description="If True, skip downloading attachments.",
        title="Skip Download",
    )


class GenerateReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    include_attachment: Optional[bool] = Field(
        False,
        description="Whether to include the event attachment in the report.",
        title="Include Attachment",
    )


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class FeatureSetQuery(BaseModel):
    featureset_name: constr(min_length=1) = Field(
        ...,
        description="Display name of the featureset exactly as it appears in EarthRanger e.g. 'Boundaries'.",
        title="Featureset Name",
    )


class LineStyle(BaseModel):
    color: Optional[List[str]] = Field(
        [],
        description="Line hex colour(s) e.g. ['#E63946']. Cycles across rows.",
        title="Color",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1.0, description="Line opacity 0–1.", title="Opacity"
    )
    width: Optional[float] = Field(
        2.0, description="Line width in pixels.", title="Width"
    )


class PointStyle(BaseModel):
    color: Optional[List[str]] = Field(
        [],
        description="Fill hex colour(s). For SVG icons this tints the marker. Cycles across rows.",
        title="Color",
    )
    size: Optional[float] = Field(
        None,
        description="Point radius / icon size in pixels. Leave empty to use the size set in EarthRanger.",
        title="Size",
    )


class PolygonStyle(BaseModel):
    fill_color: Optional[List[str]] = Field(
        [],
        description="Fill hex colour(s) e.g. ['#FFA500']. Cycles across rows.",
        title="Fill Color",
    )
    stroke_color: Optional[str] = Field(
        None, description="Border hex colour.", title="Stroke Color"
    )
    fill_opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1.0, description="Fill opacity 0–1.", title="Fill Opacity"
    )
    stroke_width: Optional[float] = Field(
        2.0, description="Border width in pixels.", title="Stroke Width"
    )


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: Optional[confloat(ge=0.001)] = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: Optional[confloat(gt=0.001)] = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: Optional[confloat(ge=1.0)] = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: Optional[confloat(gt=1.0)] = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class PatrolTrajectory(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: Optional[TrajectorySegmentFilter] = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class FieldModel(BaseModel):
    patrol_trajectory: Optional[PatrolTrajectory] = Field(
        None, title="Patrol Trajectory"
    )


class LayerStyle(BaseModel):
    polygon: Optional[List[PolygonStyle]] = Field(
        [],
        description="Polygon styling. Add one entry to override ER native colours.",
        max_length=1,
        title="Polygon",
    )
    line: Optional[List[LineStyle]] = Field(
        [],
        description="Line styling. Add one entry to override ER native colours.",
        max_length=1,
        title="Line",
    )
    point: Optional[List[PointStyle]] = Field(
        [],
        description="Point and icon marker styling. Add one entry to override ER native colours.",
        max_length=1,
        title="Point",
    )


class FeatureIdQuery(BaseModel):
    feature_id: str = Field(
        ...,
        description="UUID of a specific spatial feature available on EarthRanger.",
        title="Feature Id",
    )
    style: Optional[List[LayerStyle]] = Field(
        [],
        description="Optional: Override how EarthRanger spatial features are rendered on the map. If not specified, features will use their native EarthRanger colours and styling.",
        max_length=1,
        title="Style",
    )


class FeatureTypeQuery(BaseModel):
    feature_type: constr(min_length=1) = Field(
        ...,
        description="Feature type name as shown in EarthRanger e.g. 'Conservancy'.",
        title="Feature Type",
    )
    style: Optional[List[LayerStyle]] = Field(
        [],
        description="Optional: Override how EarthRanger spatial features are rendered on the map. If not specified, features will use their native EarthRanger colours and styling.",
        max_length=1,
        title="Style",
    )


class EarthRangerSource(BaseModel):
    query: Optional[Union[FeatureSetQuery, FeatureTypeQuery, FeatureIdQuery]] = Field(
        None, title="Query"
    )


class SpatialFeatures1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Optional[EarthRangerSource] = Field(
        default_factory=lambda: EarthRangerSource.model_validate({"query": None}),
        title="Source",
    )
    group_by: Optional[str] = Field(
        "type_name",
        description="Column used to group features in the map legend e.g. 'Feature Type' shows one legend entry per feature type.",
        title="Group By",
    )
    legend_title: Optional[str] = Field(
        "",
        description="Label shown in the map legend e.g. 'Park Boundary'.",
        title="Legend Title",
    )


class SpatialFeatures(BaseModel):
    spatial_features: Optional[SpatialFeatures1] = Field(None, title="")


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    er_client_name: Optional[ErClientName] = Field(None, title="Data Source")
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    base_maps: Optional[BaseMaps] = Field(None, title="Define Base Maps")
    Spatial_Features: Optional[SpatialFeatures] = Field(
        None,
        alias="Spatial Features",
        description="Fetch spatial features from EarthRanger and render them as a map layer.",
    )
    ranger_name: Optional[RangerName] = Field(None, title="Ranger Name")
    template_path: Optional[TemplatePath] = Field(None, title="Set Template Path")
    Patrol_and_Event_Types: Optional[PatrolAndEventTypes] = Field(
        None, alias="Patrol and Event Types", description=""
    )
    field_: Optional[FieldModel] = Field(None, description="")
    Patrol_Summary_Table: Optional[PatrolSummaryTable] = Field(
        None,
        alias="Patrol Summary Table",
        description="Prepare the patrol data table for the report.",
    )
    Event_Summary_Table: Optional[EventSummaryTable] = Field(
        None,
        alias="Event Summary Table",
        description="Prepare the event data table for the report.",
    )
    download_attachments: Optional[DownloadAttachments] = Field(
        None, title="Download Attachments"
    )
    generate_report: Optional[GenerateReport] = Field(
        None, title="Generate Ranger Report"
    )
